spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    url: jdbc:mysql://database:3306/communityBoard?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1234
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create
jwt:
  secret: VlwEyVBsYt9V7zSwSDWdDAq57TasASDQqDQDWdaWDdWqSADejMYcfPQye08f9XkHa



