spring:
  datasource:
    url: jdbc:mysql://localhost:3306/communityBoard?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
jwt:
  secret: VlwEyVBsYt9V7zSwSDWdDAq57TasASDQqDQDWdaWDdWqSADejMYcfPQye08f9XkHa
file:
  upload-dir: ./uploads
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG


