server:
  port: 8081

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    url: jdbc:mysql://localhost:3306/communityBoard?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: update
jwt:
  secret: VlwEyVBsYt9V7zSwSDWdDAq57TasASDQqDQDWdaWDdWqSADejMYcfPQye08f9XkHa
file:
  upload-dir: ./uploads
#logging:
#  level:
#    org.springframework.security: DEBUG
#    org.springframework.web: DEBUG



